# Generated by Django 5.2.13 on 2026-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=25)),
                ('student_email', models.EmailField(max_length=30)),
                ('batch', models.IntegerField()),
                ('courses', models.CharField(max_length=30)),
            ],
        ),
    ]
