# Generated by Django 5.2.13 on 2026-06-07 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_department_semester'),
        ('students', '0002_alter_student_batch_alter_student_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('registration_no', models.CharField(max_length=30, unique=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.department')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.semester')),
            ],
        ),
    ]
