# Generated by Django 5.2.13 on 2026-06-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('batch', models.IntegerField()),
                ('password', models.CharField(max_length=128)),
                ('re_password', models.CharField(max_length=128)),
                ('textarea', models.TextField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
