# Generated by Django 5.2.13 on 2026-06-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsinfo',
            old_name='payment',
            new_name='payments',
        ),
    ]
